ports:
  - port: 3000
    onOpen: open-preview

tasks:
  - command: bundle install && bundle exec rails server -b 0.0.0.0 -p 3000
  - command: curl -ssl https://eyk-assets.ey.io/eyk/eyk-installer.sh | bash
